name: amap_search_fluttify_example
description: Demonstrates how to use the amap_search_fluttify plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  permission_handler: ^6.1.3
  decorated_flutter: ^0.28.0-pre.1

#dependency_overrides:
#  foundation_fluttify:
#    path: /Users/yohom/Github/Me/All/fluttify/fluttify_infra/foundation_fluttify
#  amap_core_fluttify:
#    path: /Users/yohom/Github/Me/All/fluttify/amap/amap_core_fluttify/output-project/amap_core_fluttify
#  core_location_fluttify:
#    path: /Users/yohom/Github/Me/All/fluttify/fluttify_infra/core_location_fluttify

dev_dependencies:
  flutter_test:
    sdk: flutter
  amap_search_fluttify:
    path: ../

flutter:
  uses-material-design: true